# Generated by Django 4.2 on 2025-12-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
