# Generated by Django 4.2 on 2025-12-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0009_media_alter_tweet_options_tweet_edited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
