# Generated by Django 4.2 on 2025-12-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0010_tweet_is_pinned_tweet_pinned_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='is_scheduled',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='scheduled_publish_time',
        ),
    ]
